# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ lib, stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "prometheus-mdns-sd-unstable-${version}";
  version = "2018-01-22";
  rev = "14801db005282d09b90170c3704b6a02470ae4d1";

  goPackagePath = "github.com/msiebuhr/prometheus-mdns-sd";

  src = fetchFromGitHub {
    owner = "msiebuhr";
    repo = "prometheus-mdns-sd";
    inherit rev;
    sha256 = "1yjpnynkpwlrv9lnxvdkdk9vi6a4payqfjqh377blrsspz60f3ri";
  };

  goDeps = ./deps.nix;

  meta = {
    license = lib.licenses.unfree;
  };
}
