# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/hashicorp/mdns";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/mdns";
      rev = "34dc81287dc88553017c4b62c0496c6fa4e0bc89";
      sha256 = "0y3pffj44vx73qrbrgxj6mnp2xab0486ba02cpskdzmfzmgg6vxv";
    };
  }
  {
    goPackagePath = "github.com/miekg/dns";
    fetch = {
      type = "git";
      url = "https://github.com/miekg/dns";
      rev = "203ad2480beb9330454efc215d21f16c607e8174";
      sha256 = "12i2l79whv7a8c27f1dvq4wqikx4d0l30r1ja68zfgrgik6vryxq";
    };
  }
  {
    goPackagePath = "github.com/prometheus/common";
    fetch = {
      type = "git";
      url = "https://github.com/prometheus/common";
      rev = "df021da9b3f7560c0f38880d5817e9db13f63fdd";
      sha256 = "13zwn7rkdd6w6wmp2m6f0hqf7dfi8kibz1677dc0jx6m4lypb9q6";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "70a84ac30bf957c7df57edd1935d2081871515e1";
      sha256 = "0zr8np92g3qx7cdgaz4b2z5wnlym9lqyhrvs3xvv1fbsapd2z6i3";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "627f9648deb96c27737b83199d44bb5c1010cbcf";
      sha256 = "0ziz7i9mhz6dy2f58dsa83flkk165w1cnazm7yksql5i9m7x099z";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "226ff32320da7b90d0b5bc2365f4e359c466fb78";
      sha256 = "137cdvmmrmx8qf72r94pn6zxp0wg9rfl0ii2fa9jk5hdkhifiqa6";
    };
  }
]
