{
 "title": "Machine Vitals",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "NixOS Generations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "system_version_generation{instance=\"$instance\"}",
     "legendFormat": "{{release}} (stateVersion {{state}})"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NixOS Build Age",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - system_version_build_timestamp{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(node_network_transmit_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Nix store remaining",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/nix/store\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}